# Use secure Node base image
FROM node:20-alpine

# Update system packages (fix vulnerabilities)
RUN apk update && apk upgrade

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy rest of project
COPY . .

# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Switch to non-root user
USER appuser

# Expose port
EXPOSE 3000

# Run app
CMD ["node", "server.js"]